#!/usr/bin/env bash
set -euo pipefail

# Build Arch Linux package (.pkg.tar.zst) from staged server tree. Uses makepkg on Arch hosts,
# or Docker (archlinux:latest) elsewhere.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARCH="amd64"

# shellcheck source=../common/packaging-python.sh disable=SC1091
source "${ROOT}/packaging/common/packaging-python.sh"
resolve_packaging_python || exit 1

usage() {
  echo "Usage: $0 [--arch amd64|arm64]" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --arch)
      [[ $# -ge 2 ]] || usage
      ARCH="$2"
      shift 2
      ;;
    *)
      usage
      ;;
  esac
done

META="${ROOT}/packaging/out/metadata.json"
STAGE="${ROOT}/packaging/.stage/${ARCH}/server"
OUT="${ROOT}/packaging/out/${ARCH}/pacman"
ARCH_DIR="${ROOT}/packaging/arch"
WORK="${ROOT}/packaging/out/pacman-work/${ARCH}"

if [[ ! -f "${META}" ]]; then
  "${ROOT}/packaging/common/generate-metadata.sh"
fi

if [[ ! -d "${STAGE}" ]]; then
  echo "Missing staged payload ${STAGE}; run packaging/tools/stage.sh first" >&2
  exit 1
fi

VD_META_JSON="${META}"
if command -v cygpath >/dev/null 2>&1; then
  VD_META_JSON="$(cygpath -w "${META}")"
fi
export VD_META_JSON

PKG="$("${PACKAGING_PYTHON[@]}" -c "import json, os; print(json.load(open(os.environ['VD_META_JSON'], encoding='utf-8'))['package_name'])")"
VER_RAW="$("${PACKAGING_PYTHON[@]}" -c "import json, os; print(json.load(open(os.environ['VD_META_JSON'], encoding='utf-8'))['version'])")"
VER_PAC="$("${PACKAGING_PYTHON[@]}" <<'PY'
import json, os, re
v = str(json.load(open(os.environ["VD_META_JSON"], encoding="utf-8"))["version"])
v = v.replace(":", ".").replace("/", ".").replace("+", "_").replace("-", "_")
if not re.match(r"^[a-zA-Z0-9._]+$", v):
    v = re.sub(r"[^a-zA-Z0-9._]", "_", v)
print(v)
PY
)"

case "${ARCH}" in
  amd64) PAC_ARCH="x86_64" ;;
  arm64) PAC_ARCH="aarch64" ;;
  *) echo "Unsupported --arch ${ARCH}" >&2; exit 1 ;;
esac

rm -rf "${WORK}"
mkdir -p "${WORK}/pkgroot/usr/lib/videodedupserver" \
  "${WORK}/pkgroot/usr/lib/systemd/system" \
  "${WORK}/pkgroot/etc/videodedupserver" \
  "${WORK}/pkgroot/var/lib/videodedupserver" \
  "${WORK}/pkgroot/var/log/videodedupserver"

cp -a "${STAGE}/." "${WORK}/pkgroot/usr/lib/videodedupserver/"
if command -v strip >/dev/null 2>&1; then
  _sqlite="${WORK}/pkgroot/usr/lib/videodedupserver/libe_sqlite3.so"
  if [[ -f "${_sqlite}" ]]; then
    strip --strip-unneeded "${_sqlite}" 2>/dev/null || true
  fi
fi
install -m 0644 "${ROOT}/packaging/common/systemd/videodedupserver.service" \
  "${WORK}/pkgroot/usr/lib/systemd/system/videodedupserver.service"
install -m 0644 "${ROOT}/packaging/common/env/videodedupserver.env" \
  "${WORK}/pkgroot/etc/videodedupserver/env"

FW="${ROOT}/packaging/common/firewall"
mkdir -p "${WORK}/pkgroot/usr/share/doc/${PKG}" "${WORK}/pkgroot/usr/lib/${PKG}/firewall"
sed 's/\r$//' "${FW}/README.firewall" > "${WORK}/pkgroot/usr/share/doc/${PKG}/README.firewall"
chmod 0644 "${WORK}/pkgroot/usr/share/doc/${PKG}/README.firewall"
for s in open-port-ufw.sh open-port-firewalld.sh open-port-iptables.sh open-port-nftables.sh \
  configure-firewall-interactive.sh; do
  sed 's/\r$//' "${FW}/${s}" > "${WORK}/pkgroot/usr/lib/${PKG}/firewall/${s}"
  chmod 0755 "${WORK}/pkgroot/usr/lib/${PKG}/firewall/${s}"
done

install -m 0644 "${ROOT}/packaging/common/debian/copyright" \
  "${WORK}/pkgroot/usr/share/doc/${PKG}/copyright"

PKGDESC="$("${PACKAGING_PYTHON[@]}" <<'PY'
import json, os
m = json.load(open(os.environ["VD_META_JSON"], encoding="utf-8"))
s = (m.get("description_synopsis") or m["description"]).strip().replace("\n", " ")
s = s.replace('"', "'")[:120]
print(s)
PY
)"
PKGURL="$("${PACKAGING_PYTHON[@]}" -c "import json, os; print(json.load(open(os.environ['VD_META_JSON'],encoding='utf-8'))['homepage'].strip())")"

TAR_NAME="${PKG}-${VER_PAC}.tar.gz"
( cd "${WORK}/pkgroot" && tar -czf "${WORK}/${TAR_NAME}" . )

cp -f "${ARCH_DIR}/videodedupserver.install" "${WORK}/videodedupserver.install"

export BP_WORK="${WORK}" BP_PKG="${PKG}" BP_VER="${VER_PAC}" BP_ARCH="${PAC_ARCH}" \
  BP_DESC="${PKGDESC}" BP_URL="${PKGURL}" BP_TAR="${TAR_NAME}"
"${PACKAGING_PYTHON[@]}" <<'PY'
from pathlib import Path
import os
work = Path(os.environ["BP_WORK"])
pkg = os.environ["BP_PKG"]
ver = os.environ["BP_VER"]
arch = os.environ["BP_ARCH"]
desc = os.environ["BP_DESC"].replace('"', '\\"')
url = os.environ["BP_URL"].replace('"', '\\"')
tar = os.environ["BP_TAR"]
text = f"""# Generated by packaging/tools/build-pacman.sh
pkgname={pkg}
pkgver={ver}
pkgrel=1
pkgdesc="{desc}"
arch=('{arch}')
url="{url}"
license=('MIT')
depends=('ffmpeg' 'systemd' 'fontconfig' 'util-linux' 'ca-certificates' 'openssl' 'iproute2')
install=videodedupserver.install
source=("{tar}")
sha256sums=('SKIP')

package() {{
  cp -a "$srcdir/usr" "$pkgdir/"
  cp -a "$srcdir/etc" "$pkgdir/"
  cp -a "$srcdir/var" "$pkgdir/"
}}
"""
(work / "PKGBUILD").write_text(text, encoding="utf-8")
PY

# makepkg extracts source to $srcdir with contents at top level (usr, etc, var)
# Our tarball has ./usr at root — extract lands in $srcdir/usr — package() uses $srcdir/usr

run_makepkg_native() {
  ( cd "${WORK}" && makepkg -f --nocheck --syncdeps --noconfirm )
}

# Ephemeral Arch container for makepkg (docker create + cp + exec). Must always be removed:
# only an EXIT trap misses SIGINT/SIGTERM (e.g. Ctrl+C or parent docker stop), leaving a
# long-lived container if the main command was `sleep …`.
VD_PACMAN_CID=""

_vd_pacman_docker_remove() {
  [[ -n "${VD_PACMAN_CID:-}" ]] || return 0
  docker rm -f "${VD_PACMAN_CID}" >/dev/null 2>&1 || true
  VD_PACMAN_CID=""
}

run_makepkg_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "Docker required for makepkg on non-Arch hosts (makepkg not found)" >&2
    exit 1
  fi
  # Use docker cp instead of bind-mounting WORK: nested "docker run" (e.g. CI inside a
  # container) passes paths to the host daemon, so /src/... mounts are often empty/wrong.
  _vd_pacman_docker_remove
  VD_PACMAN_CID="$(docker create archlinux:latest bash -c 'exec tail -f /dev/null')"
  trap '_vd_pacman_docker_remove' EXIT
  trap '_vd_pacman_docker_remove; exit 130' INT
  trap '_vd_pacman_docker_remove; exit 143' TERM
  docker start "${VD_PACMAN_CID}" >/dev/null
  docker cp "${WORK}/." "${VD_PACMAN_CID}:/vd-pkg"
  docker exec "${VD_PACMAN_CID}" bash -ceu '
    pacman-key --init 2>/dev/null || true
    pacman-key --populate archlinux 2>/dev/null || true
    pacman -Sy --noconfirm archlinux-keyring base-devel sudo
    useradd -m builder 2>/dev/null || true
    printf "%s\n" "builder ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/videodedup-makepkg
    chmod 0440 /etc/sudoers.d/videodedup-makepkg
    chown -R builder:builder /vd-pkg
    cd /vd-pkg && sudo -u builder makepkg -f --nocheck --syncdeps --noconfirm
  '
  local _pkg
  while IFS= read -r -d "" _pkg; do
    docker cp "${VD_PACMAN_CID}:${_pkg}" "${WORK}/"
  done < <(docker exec "${VD_PACMAN_CID}" find /vd-pkg -maxdepth 1 -name '*.pkg.tar.zst' -print0 2>/dev/null || true)
  _vd_pacman_docker_remove
  trap - EXIT INT TERM
}

mkdir -p "${OUT}"
shopt -s nullglob
rm -f "${OUT}/"*.pkg.tar.zst
shopt -u nullglob

if command -v makepkg >/dev/null 2>&1; then
  run_makepkg_native
else
  run_makepkg_docker
fi

shopt -s nullglob
built=( "${WORK}/"*.pkg.tar.zst )
shopt -u nullglob
if ((${#built[@]} == 0)); then
  echo "makepkg did not produce .pkg.tar.zst in ${WORK}" >&2
  exit 1
fi
for f in "${built[@]}"; do
  mv -f "${f}" "${OUT}/"
done

rm -rf "${WORK}"
rmdir "${ROOT}/packaging/out/pacman-work" 2>/dev/null || true

echo "Built package(s) in ${OUT}"

