// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("1.0.5455.2295")]
[assembly: AssemblyFileVersion("1.0.5455.2295")]
